
from typing import TypedDict
from pydantic import BaseModel

class TavilyParams(TypedDict):
    query: str
    max_results: int

class PoliticalTopicOutput(BaseModel):
    is_political: bool
    reasoning: str

class DefenseTopicOutput(BaseModel):
    is_defense_related: bool
    reasoning: str

class SearchPlanItem(BaseModel):
    reason: str
    query: str

class SearchPlan(BaseModel):
    searches: list[SearchPlanItem]

class Summary(BaseModel):
    summary: str

class FinalReport(BaseModel):
    short_summary: str
    markdown_report: str
    follow_up_questions: list[str]

class PlannerToWriterInput(BaseModel):
    original_query: str  # The original user query string
    search_plan: SearchPlan  # The search plan generated by the Planner